[package]
name = "quantum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0"
winit = "0"
env_logger = "0"
log = "0"
pollster = "0"
